// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: telegram/telegram.proto

package telegram

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _telegram_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on PromptEvent with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *PromptEvent) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for UserId

	// no validation rules for Message

	return nil
}

// PromptEventValidationError is the validation error returned by
// PromptEvent.Validate if the designated constraints aren't met.
type PromptEventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PromptEventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PromptEventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PromptEventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PromptEventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PromptEventValidationError) ErrorName() string { return "PromptEventValidationError" }

// Error satisfies the builtin error interface
func (e PromptEventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPromptEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PromptEventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PromptEventValidationError{}

// Validate checks the field values on CallbackEvent with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *CallbackEvent) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for UserId

	// no validation rules for MessageId

	// no validation rules for EntityId

	// no validation rules for Event

	return nil
}

// CallbackEventValidationError is the validation error returned by
// CallbackEvent.Validate if the designated constraints aren't met.
type CallbackEventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CallbackEventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CallbackEventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CallbackEventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CallbackEventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CallbackEventValidationError) ErrorName() string { return "CallbackEventValidationError" }

// Error satisfies the builtin error interface
func (e CallbackEventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCallbackEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CallbackEventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CallbackEventValidationError{}

// Validate checks the field values on CommandEvent with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *CommandEvent) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for UserId

	// no validation rules for MessageId

	// no validation rules for Command

	return nil
}

// CommandEventValidationError is the validation error returned by
// CommandEvent.Validate if the designated constraints aren't met.
type CommandEventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CommandEventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CommandEventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CommandEventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CommandEventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CommandEventValidationError) ErrorName() string { return "CommandEventValidationError" }

// Error satisfies the builtin error interface
func (e CommandEventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCommandEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CommandEventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CommandEventValidationError{}
