package bot

const (
	KbCreateOrder           = "Создать заказ"
	KbActiveOrders          = "Активные заказы"
	KbItems                 = "Позиции"
	KbItemsPictogram        = "\U0001F9FE"
	KbAddItemPictogram      = "➕"
	KbRemovePictogram       = "➖"
	KbRemove                = "Удалить"
	KbEditItemPictogram     = "📝"
	KbQty                   = "Кол-во"
	KbPrice                 = "Цена"
	KbName                  = "Имя"
	KbCustomer              = "Клиент"
	KbCustomerPictogram     = "👤"
	KbCustomerEmail         = "Эл. почта"
	KbCustomerInstagram     = "Instagram"
	KbCustomerPhone         = "Телефон"
	KbBack                  = "Назад"
	KbCancel                = "Отмена"
	KbPayment               = "Оплата"
	KbPaymentPictogram      = "💸"
	KbPaymentLink           = "Ссылка"
	KbPaymentCard           = "Перевод"
	KbPaymentCash           = "Наличные"
	KbFullPayment           = "Полная оплата"
	KbPartialPayment        = "Частичная оплата"
	KbFullRefund            = "Полный возврат"
	KbPartialRefund         = "Частичный возврат"
	KbRefundPayment         = "Возврат"
	KbOrderActions          = "Заказ"
	KbOrderActionsPictogram = "⚙️"
	KbOrderDone             = "Завершить"
	KbOrderInProgress       = "В работу"
	KbOrderRestart          = "Возобновить"
	KbOrderDelete           = "Удалить"
	KbOrderEdit             = "Изменить"
	KbOrderEditDueDate      = "Срок сдачи"
	KbOrderEditDescription  = "Описание"
	KbOrderRestore          = "Восстановить"
	KbOrderCollapse         = "Свернуть"
	KbOrderExpand           = "Развернуть"
	KbOk                    = "OK"
	KbLingerieSetPictogram  = "👙"
	KbDeliveryPictogram     = "🚚"
)

const (
	KbDataItems                = "items"
	KbDataCustomer             = "customer"
	KbDataAddItem              = "order_add_item"
	KbDataRemoveItem           = "order_remove_item"
	KbDataEditItem             = "order_edit_item"
	KbDataBack                 = "back"
	KbDataCancel               = "cancel"
	KbDataPayment              = "payment"
	KbDataPaymentLink          = "payment_link"
	KbDataPaymentCard          = "payment_card"
	KbDataPaymentCash          = "payment_cash"
	KbDataFullPayment          = "full_payment"
	KbDataPartialPayment       = "partial_payment"
	KbDataFullRefund           = "full_refund"
	KbDataPartialRefund        = "partial_refund"
	KbDataRemovePayment        = "order_remove_payment"
	KbDataRefundPayment        = "order_refund_payment"
	KbDataOrderActions         = "order_actions"
	KbDataOrderDone            = "order_done"
	KbDataOrderDelete          = "order_delete"
	KbDataOrderRestart         = "order_restart"
	KbDataOrderRestore         = "order_restore"
	KbDataOrderCollapse        = "order_collapse"
	KbDataOrderExpand          = "order_expand"
	KbDataOrderEdit            = "order_edit"
	KbDataOrderEditDate        = "order_edit_date"
	KbDataOrderEditDescription = "order_edit_description"
	KbDataOrderInProgress      = "order_state_in_progress"
	KbDataDelivery             = "delivery"
	KbDataLingerieSet          = "lingerie"
	KbDataNotifyRead           = "notify_readed"
)

const (
	ReplyMerchantSuccessfulRegistered = "Регистрация прошла успешно"
	ReplyWelcome                      = "Добро пожаловать!"
	ReplyEnterItemName                = "Введите наименование"
	ReplyEnterItemPrice               = "Введите стоимость"
	ReplyEnterItemQty                 = "Введите количество"
	ReplyEnterCustomerEmail           = "Введите адрес эл. почты"
	ReplyEnterCustomerInstagram       = "Введите имя пользователя"
	ReplyEnterCustomerPhone           = "Введите номер телефона"
	ReplyEnterAmount                  = "Введите сумму"
	ReplyEnterOrderDueDate            = "Введите срок сдачи в формате ДД.ММ.ГГГГ"
	ReplyEnterOrderDescription        = "Введите описание"
)
